import os
import asyncio
import logging
from datetime import datetime, timezone
from telethon import TelegramClient, events
from sqlalchemy import select

from bot.db.database import get_session, AsyncSessionLocal
from bot.db.models import ContentSource, NewsArticle, Watchlist, IngestionLog
from bot.services.news import extract_tickers_aggressively

logger = logging.getLogger(__name__)

API_ID = os.getenv("TELEGRAM_API_ID")
API_HASH = os.getenv("TELEGRAM_API_HASH")

# We use the session file generated by login_telegram.py
# In docker, it will be in /app/sessions/bot.session
os.makedirs("sessions", exist_ok=True)
client = TelegramClient('sessions/bot', int(API_ID), API_HASH) if API_ID and API_HASH else None

async def log_ingestion(source_platform: str, source_handle: str, status: str, message: str):
    async with AsyncSessionLocal() as session:
        log_entry = IngestionLog(
            source_platform=source_platform,
            source_handle=source_handle,
            status=status,
            message=message
        )
        session.add(log_entry)
        await session.commit()

async def get_active_telegram_handles():
    async with AsyncSessionLocal() as session:
        stmt = select(ContentSource).where(
            ContentSource.is_active == True,
            ContentSource.platform == 'telegram'
        )
        result = await session.execute(stmt)
        sources = result.scalars().all()
        return [s.handle for s in sources]

async def start_telegram_streaming():
    if not client:
        logger.warning("Telegram API ID/HASH not set. Telethon streaming disabled.")
        return
        
    try:
        await client.start()
        logger.info("✅ Telethon client connected and streaming.")
    except Exception as e:
        logger.error(f"Failed to start Telethon client (missing bot.session?): {e}")
        return

    # We will hook into all new messages. 
    # Because telethon requires entity caching, we just listen to all incoming messages
    # and filter by the active handles.
    
    @client.on(events.NewMessage())
    async def handler(event):
        try:
            chat = await event.get_chat()
            if not hasattr(chat, 'username') or not chat.username:
                return
            
            sender_handle = chat.username
            active_handles = await get_active_telegram_handles()
            
            # Case insensitive check
            active_handles_lower = [h.lower() for h in active_handles]
            if sender_handle.lower() not in active_handles_lower:
                return
            
            logger.info(f"New Telegram message received from {sender_handle}")
            
            # Fetch active tickers for extraction
            async with AsyncSessionLocal() as session:
                result = await session.execute(select(Watchlist.ticker))
                active_tickers = [r for r in result.scalars().all()]
            
            content_text = event.raw_text or ""
            posted_at = event.date or datetime.now(timezone.utc)
            
            # Link generation
            message_id = event.message.id
            url = f"https://t.me/{sender_handle}/{message_id}"
            
            from bot.services.news import is_duplicate_article
            async with AsyncSessionLocal() as session:
                is_dup = await is_duplicate_article(session, content_text)
                if is_dup:
                    await log_ingestion('telegram', sender_handle, 'NO_NEW_DATA', f"Duplicate skipped: {message_id}")
                    return
            
            found_tickers = extract_tickers_aggressively(content_text, active_tickers)
            
            article = NewsArticle(
                source_platform='telegram',
                source_handle=sender_handle,
                author_name=sender_handle,
                title="",
                content=content_text[:2000],
                url=url,
                posted_at=posted_at,
                tickers_mentioned=found_tickers if found_tickers else None
            )
            
            async with AsyncSessionLocal() as session:
                try:
                    session.add(article)
                    await session.commit()
                    await log_ingestion('telegram', sender_handle, 'SUCCESS', f"Real-time ingested post {message_id}")
                except Exception as e:
                    await session.rollback()
                    await log_ingestion('telegram', sender_handle, 'ERROR', f"DB Insert Error: {str(e)}")

        except Exception as e:
            logger.error(f"Telethon message handler error: {e}")

    # Keep the client running in the background
    await client.run_until_disconnected()
